name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          pip install gitpython
          pip install mido
      - name: Remove PS3 and Wii files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Move songs_xbox folder to _ark
        run: |
          mv _songs/songs_xbox _ark/songs
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: TBRBUL-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: Remove Xbox and Wii files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
          Get-ChildItem _ark/ -recurse -include *.*_wii | remove-item
      - name: Move songs_ps3 folder to _ark
        run: |
          move _songs\songs_ps3 _ark\songs
      - name: Build ARK
        run: |
          dependencies/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP0006-BLUS30282_00-TBRBULTIM"
          $packageversion="1.00"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3
      - name: Delete USRDIR folder
        un: |
          Remove-Item -Path "_build\ps3\USRDIR" -Recurse -Force
      - name: Move PS3 eboot patch
        run: |
          move "_build\ps3 eboot patch" "_build\ps3\ps3 eboot patch"

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: TBRBUL-PS3
          path: _build/ps3
