name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Remove PS3 and Wii files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Move songs_xbox folder to _ark
        run: |
          mv _songs/songs_xbox _ark/songs
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5 -s 4073741823
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: TBRBUL-Xbox
          path: _build/xbox

  build_ps3_usa:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - name: Remove Xbox and Wii files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
          Get-ChildItem _ark/ -recurse -include *.*_wii | remove-item
      - name: Move songs_ps3 folder to _ark
        run: |
          move _songs\songs_ps3 _ark\songs
      - name: Build ARK
        run: |
          dependencies/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5 -s 4073741823
      - name: Build PKG
        run: |
          move "dependencies\ta_pkg_repacker_tools\usa\PARAM.SFO" "_build\ps3\USRDIR"
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP0006-BLUS30282_00-TBRBULTIM"
          $packageversion="1.01"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/usa/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: TBRBUL-PS3-USA
          path: '*.pkg'

  build_ps3_eur:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - name: Remove Xbox and Wii files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
          Get-ChildItem _ark/ -recurse -include *.*_wii | remove-item
      - name: Move songs_ps3 folder to _ark
        run: |
          move _songs\songs_ps3 _ark\songs
      - name: Build ARK
        run: |
          dependencies/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5 -s 4073741823
      - name: Build PKG
        run: |
          move "dependencies\ta_pkg_repacker_tools\eur\PARAM.SFO" "_build\ps3\USRDIR"
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP0006-BLES00532_00-TBRBULTIM"
          $packageversion="1.01"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/eur/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: TBRBUL-PS3-EUR
          path: '*.pkg'

  build_wii_patcher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
      - name: Remove Xbox and PS3 files
        run: |
          find . -name "*.*_xbox" -type f -delete
          find . -name "*.*_ps3" -type f -delete
      - name: Move songs_wii folder to _ark
        run: |
          mv _songs/songs_wii _ark/songs
      - name: Create necessary directories and copy files for patcher
        run: |
          mkdir -p ./_build/wii/ultimate_files/sys/
          mkdir -p ./_build/wii/ultimate_files/files/gen/
          mkdir -p ./_build/wii/iso
          mkdir -p ./_build/wii/wit
          cp dependencies/patch/main.dol ./_build/wii/ultimate_files/sys/main.dol
          cp dependencies/patch/setup.txt ./_build/wii/ultimate_files/setup.txt
          cp _build/wii_rebuild_files/main_wii.hdr ./_build/wii/ultimate_files/files/gen/main_wii.hdr
          cp -r dependencies/wii-patcher/* ./_build/wii
          cp -r dependencies/wit/* ./_build/wii/wit
          cp -r iso/* ./_build/wii/iso

      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/wii/ultimate_files/files/gen -n "patch_wii" -e -v 5 -s 4073741823
      
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: TBRBUL-Wii-Patcher
          path: _build/wii
